version: "3"


services:
  jukepi-rest-player:
    build: ./rest-player/build.sh
    image: jukepi-rest-player
    container_name: jukepi-rest-player
    network_mode: jukepi-network
    ports:
      - 8888:8888
    environment:
      - PLAYER=mock
    volumes:
      - /Users/jaivalis/Music/iTunes:/music

  jukepi:
    build: ./jukepi-ui/build.sh
    container_name: jukepi
    image: jukepi
    ports:
      - 8080:8080
    network_mode: jukepi-network
    environment:
      - PLAYER_ENDPOINT=http://jukepi-rest-player:8888
    volumes:
      - /Users/jaivalis/Music/iTunes:/music

#networks:
#  jukepi-network:
#    driver: overlay
