version: "3"


services:
  jukepi-rest-player:
    build: ./rest-player/build.sh
    image: jukepi-rest-player
    network_mode: "jukepi-network"
#    volumes:
#      - /Users/jaivalis/Music/iTunes:/music

  jukepi:
    build: ./build.sh
    image: jukepi
    network_mode: "jukepi-network"
#      volumes:
#        - /Users/jaivalis/Music/iTunes:/music

networks:
  jukepi-network:
    driver: overlay

volumes:
  data:
    external: true